apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraping
  template:
    metadata:
      labels:
        app: scraping
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/uninow/scraping/scraping:v2.0.1
          name: scraping