name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - main

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: files
        run: echo "PATHS=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
      - name: Check image existence
        uses: pucke-uninow/image-checker@v0.0.3
        with:
          token: ${{ secrets.UNINOW_GITHUB_TOKEN }}
          paths: ${{ steps.files.outputs.PATHS }}
